"""Build small update installers from recent releases to this Windows build.

Every release publishes ADF-Files-<version>-Windows.json, the size and SHA-256
of each installed file. A patch for an earlier version holds only the files
that differ from it. A file whose content already exists in that installation
under another name, such as the version-named third-party source archive, is
copied there after its hash is checked. The app downloads the patch for its own
version and otherwise the full installer. A release is never blocked: without
network access or earlier manifests only the full installer is built.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request

from release_common import version as source_version

ROOT = Path(__file__).resolve().parents[1]
RELEASES = 'https://github.com/Keilkim/ADF/releases'
API = 'https://api.github.com/repos/Keilkim/ADF/releases?per_page=30'
BASES = 3
# Above this share of the full application a patch saves too little to publish.
MAX_RATIO = 0.4
VERSION = re.compile(r'\d+\.\d+\.\d+')


def manifest_name(version):
    return f'ADF-Files-{version}-Windows.json'


def file_manifest(folder, version):
    files = {}
    for path in sorted(folder.rglob('*')):
        if path.is_file():
            with path.open('rb') as stream:
                digest = hashlib.file_digest(stream, 'sha256').hexdigest()
            files[path.relative_to(folder).as_posix()] = {'size': path.stat().st_size, 'sha256': digest}
    return {'version': version, 'files': files}


def cleaned_by_installer(path):
    """Other versions of these are deleted after installing (CurStepChanged in installer/adf.iss)."""
    return bool(re.fullmatch(r'_internal/SOURCES/ADF-(?:Source|ThirdParty-Sources)-\d+\.\d+\.\d+\.zip'
                             r'|ADFShell-\d+\.\d+\.\d+\.dll', path))


def plan(base, new):
    """Files to ship, files to copy inside the installation, and files to delete."""
    old, current = base['files'], new['files']
    # A copy source must still hold its old content while [Files] runs: either the
    # patch leaves it untouched, or the installer only deletes it afterwards.
    sources = {}
    for path, meta in old.items():
        if current.get(path, {}).get('sha256') == meta['sha256'] or (path not in current and cleaned_by_installer(path)):
            sources.setdefault(meta['sha256'], path)
    ship, copy = [], []
    for path, meta in current.items():
        if re.fullmatch(r'ADFShell-[^/]+\.dll', path):
            continue  # installer/adf.iss always installs this version's Explorer DLL.
        if old.get(path, {}).get('sha256') == meta['sha256']:
            continue
        if meta['sha256'] in sources:
            copy.append((path, sources[meta['sha256']], meta['sha256']))
        else:
            ship.append(path)
    delete = [path for path in old if path not in current and not cleaned_by_installer(path)]
    return ship, copy, delete


def windows(path):
    if any(character in path for character in '{}"\''):
        raise ValueError('Unsupported character in installed file name: ' + path)
    return path.replace('/', '\\')


def split(path):
    folder, _, name = windows(path).rpartition('\\')
    return ('{app}\\' + folder) if folder else '{app}', name


def installer_sections(base, new, ship, copy, delete):
    files = [f'; Generated by scripts/make-update-patches.py: ADF {base} to {new}']
    for path in ship:
        folder, _ = split(path)
        files.append(f'Source: "{{#AppBuildDir}}\\{windows(path)}"; DestDir: "{folder}"; Flags: ignoreversion')
    checks = []
    for path, source, digest in copy:
        folder, name = split(path)
        files.append(f'Source: "{{app}}\\{windows(source)}"; DestDir: "{folder}"; DestName: "{name}"; '
                     'Flags: external ignoreversion')
        checks.append(f"  if not PatchFileMatches('{windows(source)}', '{digest}') then begin\n"
                      f"    Result := 'Changed or missing file: {windows(source)}';\n    Exit;\n  end;")
    if delete:
        files.append('[InstallDelete]')
        files += [f'Type: files; Name: "{{app}}\\{windows(path)}"' for path in delete]
    return '\n'.join(files)+'\n', '\n'.join(checks)+'\n'


def fetch(url, token=None):
    headers = {'User-Agent': 'ADF-release-build', 'Accept': 'application/vnd.github+json'}
    if token and url.startswith('https://api.github.com/'):
        headers['Authorization'] = 'Bearer '+token
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=60) as response:
        return json.load(response)


def published_bases(current, token):
    releases = fetch(API, token)
    versions = [release['tag_name'][1:] for release in releases
                if not release['draft'] and not release['prerelease'] and VERSION.fullmatch(release['tag_name'][1:])]
    key = lambda text: tuple(map(int, text.split('.')))
    return sorted((v for v in versions if key(v) < key(current)), key=key, reverse=True)[:BASES]


def base_manifest(base, folder, token):
    local = folder/manifest_name(base) if folder else None
    if local and local.is_file():
        manifest = json.loads(local.read_text(encoding='utf-8'))
    else:
        try:
            manifest = fetch(f'{RELEASES}/download/v{base}/{manifest_name(base)}', token)
        except urllib.error.HTTPError as error:
            if error.code == 404:
                return None  # released before update patches existed
            raise
    if manifest.get('version') != base or not isinstance(manifest.get('files'), dict):
        raise RuntimeError('Malformed file manifest for '+base)
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--iscc', type=Path, required=True)
    parser.add_argument('--build', type=Path, default=ROOT/'dist/ADF')
    parser.add_argument('--output', type=Path, default=ROOT/'release')
    parser.add_argument('--version', default=source_version(ROOT))
    parser.add_argument('--bases', nargs='?', const='', help='Comma-separated versions instead of the latest published releases')
    parser.add_argument('--manifests', type=Path, help='Folder with earlier file manifests to use before downloading')
    args = parser.parse_args()
    token = os.environ.get('GH_TOKEN') or os.environ.get('GITHUB_TOKEN')
    args.output.mkdir(parents=True, exist_ok=True)
    for stale in args.output.glob(f'ADF-Update-*-to-{args.version}.exe'):
        stale.unlink()
    manifest = file_manifest(args.build, args.version)
    (args.output/manifest_name(args.version)).write_text(json.dumps(manifest, indent=1)+'\n', encoding='utf-8')
    total = sum(meta['size'] for meta in manifest['files'].values())
    try:
        bases = [base for base in args.bases.split(',') if base] if args.bases is not None else published_bases(args.version, token)
    except (OSError, ValueError) as error:
        print(f'WARNING: earlier releases unavailable ({error}); only the full installer is published.')
        return 0
    work = ROOT/'build/update-patches'
    shutil.rmtree(work, ignore_errors=True)
    for base in bases:
        try:
            previous = base_manifest(base, args.manifests, token)
        except (OSError, ValueError) as error:
            print(f'WARNING: no patch from {base}: {error}')
            continue
        if previous is None:
            print(f'No patch from {base}: that release has no file manifest.')
            continue
        ship, copy, delete = plan(previous, manifest)
        shipped = sum(manifest['files'][path]['size'] for path in ship)
        if shipped > MAX_RATIO*total:
            print(f'No patch from {base}: {shipped/2**20:.0f} MiB changed; the full installer is smaller to maintain.')
            continue
        folder = work/base
        folder.mkdir(parents=True)
        files, checks = installer_sections(base, args.version, ship, copy, delete)
        (folder/'files.iss').write_text(files, encoding='utf-8')
        (folder/'checks.iss').write_text(checks, encoding='utf-8')
        command = [str(args.iscc), '/Qp', f'/DPatchFrom={base}', f'/DPatchDir={folder}',
                   f'/DAppVersion={args.version}', f'/DAppBuildDir={args.build.resolve()}',
                   f'/O{args.output.resolve()}', str(ROOT/'installer/adf.iss')]
        subprocess.run(command, check=True)
        patch = args.output/f'ADF-Update-{base}-to-{args.version}.exe'
        print(f'{patch.name}: {len(ship)} files, {len(copy)} reused, {len(delete)} removed, '
              f'{patch.stat().st_size/2**20:.1f} MiB')
    return 0


if __name__ == '__main__':
    sys.exit(main())
